### ISSUE TITLE
AMI builds are failing to install `awscli`

### ISSUE THREAD

**Issue by kkeshavamurthy** [kubernetes-sigs/image-builder#1026]
**What steps did you take and what happened:**
make build-ami-ubuntu-2004

```
    ubuntu-20.04: TASK [providers : include_tasks] ***********************************************
    ubuntu-20.04: included: /Users/kkeshavamurt/workspace/image-builder/images/capi/ansible/roles/providers/tasks/aws.yml for default
    ubuntu-20.04:
    ubuntu-20.04: TASK [providers : install aws clients] *****************************************
    ubuntu-20.04: fatal: [default]: FAILED! => {"changed": false, "cmd": ["/usr/bin/pip3", "install", "awscli"], "msg": "stdout: Collecting awscli\n  Downloading awscli-1.27.21-py3-none-any.whl (3.9 MB)\n\n:stderr: ERROR: Could not find a version that satisfies the requirement botocore==1.29.21 (from awscli) (from versions: 0.4.1, 0.4.2, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.6.0, 0.7.0, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.9.0, 0.9.1, 0.9.2, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.15.0, 0.15.1, 0.16.0, 0.17.0, 0.18.0, 0.19.0, 0.20.0, 0.21.0, 0.22.0, 0.23.0, 0.24.0, 0.25.0, 0.26.0, 0.27.0, 0.28.0, 0.29.0, 0.30.0, 0.31.0, 0.32.0, 0.33.0, 0.34.0, 0.35.0, 0.36.0, ...
...
...
...
...
...
1.29.6, 1.29.7, 1.29.8, 1.29.9, 1.29.10, 1.29.11, 1.29.12, 1.29.13, 1.29.14, 1.29.15, 1.29.16, 1.29.17, 1.29.18, 1.29.19, 1.29.20)\nERROR: No matching distribution found for botocore==1.29.21 (from awscli)\n"}
    ubuntu-20.04:
    ubuntu-20.04: PLAY RECAP *********************************************************************
    ubuntu-20.04: default                    : ok=17   changed=11   unreachable=0    failed=1    skipped=121  rescued=0    ignored=0
    ubuntu-20.04:

```
**What did you expect to happen:**
Build Successfully

**Anything else you would like to add:**
Upgrading the pip3 version to latest seems to fix the issue. 

```
   ubuntu-20.04:
    ubuntu-20.04: TASK [providers : upgrade pip to latest] ***************************************
    ubuntu-20.04: changed: [default]
    ubuntu-20.04:
    ubuntu-20.04: TASK [providers : install aws clients] *****************************************
    ubuntu-20.04: changed: [default]
    ubuntu-20.04:
    ubuntu-20.04: TASK [providers : install aws agents Ubuntu] ************************
```

**Environment:**

Project ([Image Builder for Cluster API](https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi), [kube-deploy/imagebuilder](https://github.com/kubernetes-sigs/image-builder/tree/master/images/kube-deploy/imagebuilder), [konfigadm](https://github.com/kubernetes-sigs/image-builder/tree/master/images/konfigadm)):

Additional info for Image Builder for Cluster API related issues:

- OS (e.g. from `/etc/os-release`, or `cmd /c ver`):
- Packer Version:
- Packer Provider:
- Ansible Version: 
- Cluster-api version (if using):
- Kubernetes version: (use `kubectl version`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
