### ISSUE TITLE
capi image-builder broken

### ISSUE THREAD

**Issue by figo** [kubernetes-sigs/image-builder#109]
Looks like due to PR https://github.com/kubernetes-sigs/image-builder/pull/68 merged

particularly 
```
  set_fact:
    ecr: "{{ kubernetes_container_registry is regex('^[0-9]{12}.dkr.ecr.[^.]+.amazonaws.com\/') }}"
```

error log:
```
[0;32m    ubuntu-1804: ERROR! Syntax Error while loading YAML.[0m
[0;32m    ubuntu-1804:   found unknown escape character[0m
[0;32m    ubuntu-1804:[0m
[0;32m    ubuntu-1804: The error appears to be in '/home/imgbuilder-ova/workspace/run-image-builder/62/image-builder/images/capi/ansible/roles/kubernetes/tasks/main.yml': line 40, column 92, but may[0m
[0;32m    ubuntu-1804: be elsewhere in the file depending on the exact syntax problem.[0m
[0;32m    ubuntu-1804:[0m
[0;32m    ubuntu-1804: The offending line appears to be:[0m
[0;32m    ubuntu-1804:[0m
[0;32m    ubuntu-1804:   set_fact:[0m
[0;32m    ubuntu-1804:     ecr: "{{ kubernetes_container_registry is regex('^[0-9]{12}.dkr.ecr.[^.]+.amazonaws.com\/') }}"[0m
[0;32m    ubuntu-1804:                                                                                            ^ here[0m
[0;32m    ubuntu-1804: We could be wrong, but this one looks like it might be an issue with[0m
[0;32m    ubuntu-1804: missing quotes. Always quote template expression brackets when they[0m
[0;32m    ubuntu-1804: start a value. For instance:[0m

```

cc @aaroniscode

**Comment by aaroniscode** [comment]
Hmmm.... I just built a bunch of images last night running off master.  I wonder if this is specific to an Ansible version. What version of Ansible are you using?

Last night I also ran only against Amazon Linux 2. I'll try again with Ubuntu and see if I can reproduce.

**Comment by figo** [comment]
Believe we are using Ansible 2.8.3.

**Comment by aaroniscode** [comment]
@figo I'm using Ansible 2.8.3 as well, so that's not it. Trying a build with Ubuntu.

**Comment by ncdc** [comment]
I upgraded to 2.9.2 locally and the regex works and there are no errors with a simple playbook test:

```
---
- hosts: 127.0.0.1
  connection: local
  vars:
    kubernetes_container_registry: "123456789012.dkr.ecr.foobar.amazonaws.com/asdf"
  tasks:
  - name: andy
    set_fact:
     ecr: "{{ kubernetes_container_registry is regex('^[0-9]{12}.dkr.ecr.[^.]+.amazonaws.com\/') }}"

```
