### ISSUE TITLE
Replace usage of `apt_key` in ansible tasks

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/image-builder#1293]
**Is your feature request related to a problem? Please describe.**

Image builder is using the Ansible [`apt_key`](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_key_module.html) module, but it is deprecated as specified in the module [notes](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_key_module.html#notes). It may stop working with Ubuntu 24.04.

**Describe the solution you'd like**

A more future-proof way is using the [`get_url`](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html) module as described in [this blog post](https://www.jeffgeerling.com/blog/2022/aptkey-deprecated-debianubuntu-how-fix-ansible), for example.

I tried that approach in #1280 but could not get it to work on Ubuntu 20.04, only 22.04, so I stuck with the working `apt_key` approach for now.

**Describe alternatives you've considered**

**Additional context**

/kind feature

**Comment by cunningr** [comment]
Today we seem to be hitting an issue related to this whilst trying to build Ubuntu 22.04:
```
    qemu: TASK [kubernetes : Add the Kubernetes repo key] ********************************
    qemu: fatal: [default]: FAILED! => {"after": ["D94AA3F0EFE21092", "871920D1991BC93C"], "before": ["D94AA3F0EFE21092", "871920D1991BC93C"], "changed": true, "fp": "234654DA9A296436", "id": "234654DA9A296436", "key_id": "234654DA9A296436", "msg": "apt-key did not return an error, but failed to add the key (check that the id is correct and *not* a subkey)", "short_id": "9A296436"}
    qemu:
    qemu: PLAY RECAP *********************************************************************
    qemu: default                    : ok=39   changed=32   unreachable=0    failed=1    skipped=293  rescued=0    ignored=0
```
