### ISSUE TITLE
Ansible shell commands should `set -o pipefail` when needed

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/image-builder#1341]
**What steps did you take and what happened:**

Run `make -C images/capi lint` and notice that the project is ignoring a few linter warnings of the type `risky-shell-pipe: Shells that use pipes should set the pipefail option.`

This is generally easy to fix by adding `set -o pipefail` at the beginning of a shell script:

```yaml
- name: Get installed packages
  shell: |
    set -o pipefail
    tdnf list installed | cut -d ' ' -f 1
  register: packages
```

**What did you expect to happen:**

The linter shouldn't report any of this type of warning.

**Anything else you would like to add:**

Here's one way to fix it:

```shell
cd images/capi
rm .ansible-lint-ignore  # so the linter reports existing issues
ansible-lint --tags=risky-shell-pipe ansible
# Edit the code flagged in each of the "risky-shell-pipe" warnings
# and re-run the above command until the warnings are gone. Then,
make lint-ignore
git add .
git commit -m "Ansible shell commands set -o pipefail when needed"
```

/kind bug
