### ISSUE TITLE
trivial tinkerbell action causes cluster creation hangs

### ISSUE THREAD

**Issue by ygao-armada** [kubernetes-sigs/image-builder#1397]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
I try to add a trivial action right after the action "stream-image":
```
      - environment:
          BLOCK_DEVICE: /dev/sda2
          CHROOT: "y"
          CMD_LINE: umount -f /dev/sda2
          DEFAULT_INTERPRETER: /bin/sh -c
          FS_TYPE: ext4
        image: public.ecr.aws/eks-anywhere/tinkerbell/hub/cexec:6c0f0d437bde2c836d90b000312c8b25fa1b65e1-eks-a-41
        name: trivial-cmds0
        timeout: 90
      - environment:
          BLOCK_DEVICE: /dev/sda2
          CHROOT: "y"
          CMD_LINE: mount -t ext4 /dev/sda2 /
          DEFAULT_INTERPRETER: /bin/sh -c
          FS_TYPE: ext4
        image: public.ecr.aws/eks-anywhere/tinkerbell/hub/cexec:6c0f0d437bde2c836d90b000312c8b25fa1b65e1-eks-a-41
        name: trivial-cmds1
        timeout: 90
```
However, the cluster creation command hangs.
Am I missing something? (edited) 

**What did you expect to happen:**
I expect the cluster creation will succeeds.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

Project ([Image Builder for Cluster API](https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi):

Additional info for Image Builder for Cluster API related issues:

- OS (e.g. from `/etc/os-release`, or `cmd /c ver`): Ubuntu "20.04.6 LTS (Focal Fossa)"
- Packer Version:
- Packer Provider:
- Ansible Version:
- Cluster-api version (if using):
- Kubernetes version: (use `kubectl version`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
