### ISSUE TITLE
Failes to build proxmox-ubuntu-2404 - 

### ISSUE THREAD

**Issue by nilsherzig** [kubernetes-sigs/image-builder#1562]
## Environment

- **Make target:** `make build-proxmox-ubuntu-2404`
- **Run using container image? (Y/N):** N
- **Environment vars:**
```
export PROXMOX_URL="https://10.10.10.200:8006/api2/json"
export PROXMOX_USERNAME=USER@pam!TAG
export PROXMOX_TOKEN=TOKEN
export PROXMOX_NODE="pve1"
export PROXMOX_ISO_POOL="local"
export PROXMOX_BRIDGE="vmbr0"
export PROXMOX_STORAGE_POOL="local-lvm"
```
- **Vars file:**
```

```

## What steps did you take and what happened?

1. export env vars
2. run `make build-proxmox-ubuntu-2404`
3. get check error `Service: networkd-dispatcher: running:\nExpected\n    \u003cbool\u003e: false\nto equal\n    \u003cbool\u003e: true`

## What did you expect to happen?

Successful creation of a template on my Proxmox host

## Relevant log output

<details>
<summary>Log Output</summary>

[log.txt](https://github.com/user-attachments/files/16907995/log.txt)

</details>

## Anything else you would like to add?
Same problem when using the provided packer version.

---

/kind bug

**Comment by nilsherzig** [comment]
One sec, I'm going to start `netword-dispatcher` in `proxmox.yaml`. Will report back.

**Comment by AverageMarcus** [comment]
Ah, I suspect we're missing the following from the Proxmox.yaml like you say
```
- name: Install networkd-dispatcher service (Run networkd-dispatcher)
  ansible.builtin.systemd:
    name: networkd-dispatcher
    state: started
    enabled: true
```
