### ISSUE TITLE
Openstack goss failing networkd-dispatcher

### ISSUE THREAD

**Issue by nilpntr** [kubernetes-sigs/image-builder#1626]
When trying to build using `make build-openstack-ubuntu-2404` goss failed. Goss was failing because networkd-dispatcher wasn't running:
```shell
openstack:         {
    openstack:             "duration": 44706105,
    openstack:             "err": null,
    openstack:             "expected": [
    openstack:                 "true"
    openstack:             ],
    openstack:             "found": [
    openstack:                 "false"
    openstack:             ],
    openstack:             "human": "Expected\n    \u003cbool\u003e: false\nto equal\n    \u003cbool\u003e: true",
    openstack:             "meta": null,
    openstack:             "property": "running",
    openstack:             "resource-id": "networkd-dispatcher",
    openstack:             "resource-type": "Service",
    openstack:             "result": 1,
    openstack:             "successful": false,
    openstack:             "summary-line": "Service: networkd-dispatcher: running:\nExpected\n    \u003cbool\u003e: false\nto equal\n    \u003cbool\u003e: true",
    openstack:             "test-type": 0,
    openstack:             "title": ""
    openstack:         },
```

This occurs because networkd-dispatcher is missing in the `openstack.yml` file:
```yaml
- name: Install networkd-dispatcher service (Run networkd-dispatcher)
  ansible.builtin.systemd:
    name: networkd-dispatcher
    state: started
    enabled: true
```
