### ISSUE TITLE
Prepare audit log with appropriate permissions

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/image-builder#191]
To enable auditing in Kubernetes, ideally would have this go to `/var/log/kubernetes/audit/audit*.log`

This would be done by setting the `extraVolumes` options on kubeadm, however the default permissions are not suitable for audit logs.

By prepping the file with appropriate permissions beforehand, Kubernetes API Server keeps the audit log secure.

The following should be sufficient:

``` yaml
- name: directory.logs.kubernetes
  file:
    path: /var/log/kubernetes
    state: directory
- name: kubernetes.log.audit
  file:
    path: /var/log/kubernetes/audit.log
    state: touch
    mode: "0700"
    owner: root
    group: root
```
