### ISSUE TITLE
Building Ubuntu image flakes out during installation of packages. 

### ISSUE THREAD

**Issue by kkeshavamurthy** [kubernetes-sigs/image-builder#350]
When building the Ubuntu images I'm often seeing it error out in this step:

```
    vhd-ubuntu-2004: TASK [setup : perform a dist-upgrade] ******************************************
    vhd-ubuntu-2004: changed: [default]
    vhd-ubuntu-2004:
    vhd-ubuntu-2004: TASK [setup : install baseline dependencies] ***********************************
    vhd-ubuntu-2004: fatal: [default]: FAILED! => {"changed": false, "msg": "No package matching 'conntrack' is available"}
    vhd-ubuntu-2004:
    vhd-ubuntu-2004: PLAY RECAP *********************************************************************
    vhd-ubuntu-2004: default                    : ok=4    changed=3    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0
    vhd-ubuntu-2004:
```

`conntrack` package is available in all Ubuntu versions. Need to investigate why we are seeing this behavior inconsistently.

**Comment by kkeshavamurthy** [comment]
Just to make sure it's not a `conntrack` issue, I removed it from the deb list and the build errored out with the next pkg on the list. 

```
    vhd-ubuntu-2004: TASK [setup : install baseline dependencies] ***********************************
    vhd-ubuntu-2004: fatal: [default]: FAILED! => {"changed": false, "msg": "No package matching 'ebtables' is available"}
    vhd-ubuntu-2004:
    vhd-ubuntu-2004: PLAY RECAP *********************************************************************
    vhd-ubuntu-2004: default                    : ok=4    changed=3    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0
```

So I guess something wrt apt is not ready by the time we start installing packages. 
Is retry an acceptable workaround for this?

CC: @codenrhoden @CecileRobertMichon  @EleanorRigby
