### ISSUE TITLE
Delete log files that end in .1 from the machine

### ISSUE THREAD

**Issue by voor** [kubernetes-sigs/image-builder#381]
Recently https://github.com/kubernetes-sigs/image-builder/pull/331 went in which is a vast improvement in the log behavior, but some logs are rotated by appending a number rather than targz the files.  Just add another entry -- or get fancy with regex for numbers -- to remove anything with a `.1` after it:

```
- name: Delete all logrotated log by rename
  shell:
    cmd: |
      find /var/log -type f -name '*.1' -exec rm {} +
```
