### ISSUE TITLE
Migrate ova-build.py into  CLI

### ISSUE THREAD

**Issue by moshloop** [kubernetes-sigs/image-builder#505]
OVA building/uploading is a generic enough function that makes sense to migrate this into the CLI.

e.g. `image-builder ova build -c config.yml disk.vmdk `

```yaml
ova:
    eula: LOCAL_OR_REMOTE_PATH
    streamOptimize: true
    disk: 50
    memory: 8192
    cpu: 2
    vmx_version: 15
    properties:
        PRODUCT: abc
        ANNOTATION:  Produced by Kubernetes Sigs Image Builder
```

/kind feature
