### ISSUE TITLE
windowz: print url during downloads 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/image-builder#602]
**Is your feature request related to a problem? Please describe.**

Right now we download windows assets, but we 

- dont show the url we're using
- dont show the size of the final assets

Would be nice if we had some metadata about the downlaoded assets....

```
    vmware-iso:
    vmware-iso: TASK [kubernetes : Download kubernetes binaries] *******************************
    vmware-iso: changed: [default] => (item=kubeadm)
    vmware-iso: changed: [default] => (item=kubectl)
    vmware-iso: changed: [default] => (item=kubelet)
    vmware-iso:
    vmware-iso: TASK [kubernetes : Add kubernetes folder to path] ******************************
    vmware-iso: changed: [default]
    vmware-iso:
```
doesnt show the download urls for windows bits 

**Describe the solution you'd like**
 
print the full url of the download so we now where were getting bits from and that we configured ansible to talk to the right *burrito* :)

**Comment by jayunit100** [comment]
so, `win_get_url` is a canned ansible task i guess?
not sure how to approach this but, the pertinent file i think is

maybe somethin like....?
```
- name: print kubefile sizes
  ansible.windows.win_stat:
    path: C:\k\
  register: file_info
```
