### ISSUE TITLE
Python not found

### ISSUE THREAD

**Issue by kbreit** [kubernetes-sigs/image-builder#630]
**What steps did you take and what happened:**
I'm developing a CICD pipeline to use image-builder and receiving an error:

```
User's Python3 binary directory must be in $PATH
Location of package is:
Location: /root/.local/lib/python3.8/site-packages
$PATH is currently: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
make: *** [Makefile:86: deps-ova] Error 1
```

**What did you expect to happen:**
I didn't expect the error as I do install python3 as part of the pipeline.

**Anything else you would like to add:**
Pipeline is run in gitlab-runner and is as follows:

```
build-kubernetes-image:
  image: ubuntu:latest
  stage: build
  only:
    changes:
      - kubernetes/image-builder/**
  script:
    - apt update
    - apt install git make python3 curl python3-distutils python3-pip -y
    - mkdir /opt/image-builder
    - git clone https://github.com/kubernetes-sigs/image-builder.git --branch v0.1.9 /opt/image-builder
    - mv kubernetes/image-builder/config.json /opt/image-builder/images/capi/config.json
    - cd /opt/image-builder/images/capi/
    - make deps-ova
    - PACKER_VAR_FILES=config.json make build-node-ova-vsphere-ubuntu-2004
```

**Environment:**

Project ([Image Builder for Cluster API](https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi), [kube-deploy/imagebuilder](https://github.com/kubernetes-sigs/image-builder/tree/master/images/kube-deploy/imagebuilder), [konfigadm](https://github.com/kubernetes-sigs/image-builder/tree/master/images/konfigadm)):

Additional info for Image Builder for Cluster API related issues:

- OS (e.g. from `/etc/os-release`, or `cmd /c ver`): `  image: ubuntu:latest`
- Packer Version: Version installed by `make deps`
- Packer Provider: Version installed by `make deps`
- Ansible Version: Version installed by `make deps`
- Cluster-api version (if using):
- Kubernetes version: (use `kubectl version`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]
